[build]
  publish = "."
  command = ""

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDrzSgCHn53kfa4dJJVJhDD717v8SPozR0"
  VITE_FIREBASE_AUTH_DOMAIN = "naija-truths.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "naija-truths"
  VITE_FIREBASE_STORAGE_BUCKET = "naija-truths.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "476936659655"
  VITE_FIREBASE_APP_ID = "1:476936659655:web:0df8b9419012dac9e014e2"
  VITE_FIREBASE_MEASUREMENT_ID = "G-69WH8S8X8H"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"